[package]
name = "leaves"
version = "0.2.1"
authors = ["lsongzhi <lsongzhi@163.com>"]
edition = "2018"
repository = "https://github.com/songzhi/leaves"
readme = "README.md"
keywords = ["distribution", "id"]
license = "MIT"
description = "Distributed ID Generation Service"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
mysql = ["mysql_async"]
redis = ["redis-async"]

[dependencies]
tokio = { version="0.2.8", features=["time", "rt-core", "sync"] }
async-trait = "0.1"
log = "0.4"
pretty_env_logger = "0.3"
lockfree = "0.5"
mysql_async = { version="0.21", optional=true }
redis-async = { version="0.6", optional=true }

[[example]]
name = "redis"
path = "examples/redis.rs"
required-features = ["redis"]

[[example]]
name = "mysql"
path = "examples/mysql.rs"
required-features = ["mysql"]