[package]
name = "leaves"
version = "0.2.0"
authors = ["lsongzhi <lsongzhi@163.com>"]
edition = "2018"
repository = "https://github.com/songzhi/leaves"
readme = "README.md"
keywords = ["distribution", "id"]
license = "MIT"
description = "Distributed ID Generation Service"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
mysql = ["mysql_async"]
redis = ["redis-async"]

[dependencies]
tokio = { version="0.2.2", features=["time", "rt-core"] }
async-trait = "0.1.19"
async-std = "1.2.0"
log = "0.4"
pretty_env_logger = "0.3"
lockfree = "0.5.1"
mysql_async = { version="0.21.0", optional=true }
redis-async = { version="0.6.1", optional=true }

[dev-dependencies]
tokio = { version="0.2.2", features=["time", "rt-core", "macros"] }